### PR TITLE
Sleep if get response code 429 - too many requests

### PR DESCRIPTION
**Pull request by KevinXL**
Sleep 1 minute if get response code 429 - too many requests

### CODE REVIEW

**Comment by jacobdekeizer** [comment]
You should catch the CcvShopException and read the status code in your own implementation. When you get the 429 status code you can add a sleep in your own code and retry the request.

**Comment by KevinXL** [comment]
Sure I can, but than I need to do it add many places. This fix will automatic do it for all requests.

**Comment by jacobdekeizer** [comment]
With this fix we force the php process to wait 60 seconds which can be fine in your use case, but there are use cases where this isn't a wanted scenario (f.e. read realtime API data). Maybe you can think of a way that you don't repeat your code or another fix for this problem :)

**Comment by jacobdekeizer** [comment]
@KevinXL I have an idea how we can fix this. If we add an enableWaitAndRetry and a disableWaitAndRetry method to the client class we can optionally enable this functionality. When waitAndRetry is enabled, you can execute the if statement. Let me know what you think.

**Comment by KevinXL** [comment]
@jacobdekeizer That is an option, we can also take a look for a middleware in Guzzle something like https://github.com/caseyamcl/guzzle_retry_middleware

**Comment by jacobdekeizer** [comment]
@KevinXL This is possible through the setClient method on the Client. Here you can provide your own guzzle client with the retry options. I made a little improvement on master (v0.9.0) so you can easily add your own guzzle client.

**Pull request closed without merging**
