### PR TITLE
PHP minimum version to 7.3; PSR12 styling

### PR DESCRIPTION
**Pull request by sandcore-dev**
Here are the corrections to `composer.json` we agreed about. I've also applied the code styles.

I also noticed the endpoint classes had incomplete docblocks. Since I don't like all those squiggles PhpStorm puts up, I usually autocomplete them. Do you mind if I correct those docblocks in this PR?

### CODE REVIEW

**Comment by sandcore-dev** [comment]
There's a build error because composer.lock is not up-to-date. I don't think composer.lock belongs in a library, though.

**Comment by jacobdekeizer** [comment]
Yes, the composer.lock should be removed and added to the .gitignore. Feel free to add it here.

**Comment by jacobdekeizer** [comment]
@sandcore-dev I changed my phpstorm settings to only add the throws docblock, because the default generated docblock doesn't add usefull information. It's only useful when the parameter has additional information, such as the models. But it's not consistent yet everywhere, I'm planning to make the code more consistent, but didn't have the time for it yet. I would also like to add strict types everywhere etc. I'm happy with your contributions to make the package better :)

**Comment by jacobdekeizer** [comment]
Thank you!

**Pull request merged**
